blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include("post.urls", namespace='post')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_home,
	post_update,
	post_detail,
	post_delete,
	post_create,
	)

urlpatterns = [
	url(r'^$', post_home, name='home'),
	url(r'^create/$', post_create),
	url(r'^(?P<id>\d+)/edit/$', post_update, name="update"),
	url(r'^(?P<id>\d+)/$', post_detail, name='detail'),
	url(r'^(?P<id>\d+)/delete/$',  post_delete, name='delete'),

]

static_cdn/blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include("post.urls", namespace='post')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

class post(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	image =models.FileField(upload_to=upload_location,null=True, blank=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	author = models.CharField(max_length= 20 ,null = True)
	email = models.EmailField(max_length = 100, null= True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("post:detail", kwargs={"id": self.id})

static_cdn/static_cdn/post/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

class post(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	image =models.FileField(upload_to=upload_location,null=True, blank=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	author = models.CharField(max_length= 20 ,null = True)
	email = models.EmailField(max_length = 100, null= True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("post:detail", kwargs={"id": self.id})

static_cdn/static_cdn/static_cdn/post/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

class post(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	image =models.FileField(upload_to=upload_location,null=True, blank=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	author = models.CharField(max_length= 20 ,null = True)
	email = models.EmailField(max_length = 100, null= True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("post:detail", kwargs={"id": self.id})

static_cdn/static_cdn/static_cdn/static_cdn/post/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

class post(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	image =models.FileField(upload_to=upload_location,null=True, blank=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	author = models.CharField(max_length= 20 ,null = True)
	email = models.EmailField(max_length = 100, null= True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("post:detail", kwargs={"id": self.id})

post/forms.py
from django import forms

from .models import post

class postform(forms.ModelForm):
	class Meta:
		model = post
		fields = [
			"title",
			"content",
			"image",
			"author",
			"email"
		]

static_cdn/static_cdn/post/forms.py
from django import forms

from .models import post

class postform(forms.ModelForm):
	class Meta:
		model = post
		fields = [
			"title",
			"content",
			"image",
			"author",
			"email"
		]

static_cdn/static_cdn/static_cdn/post/forms.py
from django import forms

from .models import post

class postform(forms.ModelForm):
	class Meta:
		model = post
		fields = [
			"title",
			"content",
			"image",
			"author",
			"email"
		]

static_cdn/static_cdn/static_cdn/static_cdn/post/forms.py
from django import forms

from .models import post

class postform(forms.ModelForm):
	class Meta:
		model = post
		fields = [
			"title",
			"content",
			"image",
			"author",
			"email"
		]

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.contrib import messages
from .models import post
from .forms import postform
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_create(request):
	
	form = postform(request.POST or None, request.FILES or None);
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)
def post_home(request):
	queryset_list= post.objects.all().order_by("-timestamp")
	paginator = Paginator(queryset_list, 5)
	page_request_var = 'page'
	page = request.GET.get(page_request_var)

	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)
	
	context = {
		"object_list":queryset,
		"title": "list",
		"page_request_var":page_request_var,
	}
	return render(request, "base.html", context)



def post_detail(request, id=None):
	instance = get_object_or_404(post, id=id)
	
	context={
		"title": instance.title,
		"instance": instance,
		

	}
	return render(request, "post_detail.html", context)


def post_update(request, id = None):
	instance = get_object_or_404(post, id= id)
	form = postform(request.POST or None,  request.FILES or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": instance.title,
			"instance": instance,
			"form": form,

		}
	return render(request, "post_form.html",context)

def post_delete(request, id=None):
	instance = get_object_or_404(post, id= id)
	instance.delete()
	messages.success(request,"save!!", extra_tags='some-tag')
	return redirect("post:home")

static_cdn/static_cdn/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.contrib import messages
from .models import post
from .forms import postform
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_create(request):
	
	form = postform(request.POST or None, request.FILES or None);
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)
def post_home(request):
	queryset_list= post.objects.all().order_by("-timestamp")
	paginator = Paginator(queryset_list, 5)
	page_request_var = 'page'
	page = request.GET.get(page_request_var)

	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)
	
	context = {
		"object_list":queryset,
		"title": "list",
		"page_request_var":page_request_var,
	}
	return render(request, "base.html", context)



def post_detail(request, id=None):
	instance = get_object_or_404(post, id=id)
	
	context={
		"title": instance.title,
		"instance": instance,
		

	}
	return render(request, "post_detail.html", context)


def post_update(request, id = None):
	instance = get_object_or_404(post, id= id)
	form = postform(request.POST or None,  request.FILES or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": instance.title,
			"instance": instance,
			"form": form,

		}
	return render(request, "post_form.html",context)

def post_delete(request, id=None):
	instance = get_object_or_404(post, id= id)
	instance.delete()
	messages.success(request,"save!!", extra_tags='some-tag')
	return redirect("post:home")

static_cdn/static_cdn/static_cdn/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.contrib import messages
from .models import post
from .forms import postform
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_create(request):
	
	form = postform(request.POST or None, request.FILES or None);
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)
def post_home(request):
	queryset_list= post.objects.all().order_by("-timestamp")
	paginator = Paginator(queryset_list, 5)
	page_request_var = 'page'
	page = request.GET.get(page_request_var)

	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)
	
	context = {
		"object_list":queryset,
		"title": "list",
		"page_request_var":page_request_var,
	}
	return render(request, "base.html", context)



def post_detail(request, id=None):
	instance = get_object_or_404(post, id=id)
	
	context={
		"title": instance.title,
		"instance": instance,
		

	}
	return render(request, "post_detail.html", context)


def post_update(request, id = None):
	instance = get_object_or_404(post, id= id)
	form = postform(request.POST or None,  request.FILES or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": instance.title,
			"instance": instance,
			"form": form,

		}
	return render(request, "post_form.html",context)

def post_delete(request, id=None):
	instance = get_object_or_404(post, id= id)
	instance.delete()
	messages.success(request,"save!!", extra_tags='some-tag')
	return redirect("post:home")

static_cdn/static_cdn/static_cdn/static_cdn/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.contrib import messages
from .models import post
from .forms import postform
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_create(request):
	
	form = postform(request.POST or None, request.FILES or None);
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)
def post_home(request):
	queryset_list= post.objects.all().order_by("-timestamp")
	paginator = Paginator(queryset_list, 5)
	page_request_var = 'page'
	page = request.GET.get(page_request_var)

	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)
	
	context = {
		"object_list":queryset,
		"title": "list",
		"page_request_var":page_request_var,
	}
	return render(request, "base.html", context)



def post_detail(request, id=None):
	instance = get_object_or_404(post, id=id)
	
	context={
		"title": instance.title,
		"instance": instance,
		

	}
	return render(request, "post_detail.html", context)


def post_update(request, id = None):
	instance = get_object_or_404(post, id= id)
	form = postform(request.POST or None,  request.FILES or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request,"save!!", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": instance.title,
			"instance": instance,
			"form": form,

		}
	return render(request, "post_form.html",context)

def post_delete(request, id=None):
	instance = get_object_or_404(post, id= id)
	instance.delete()
	messages.success(request,"save!!", extra_tags='some-tag')
	return redirect("post:home")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProBlogger</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">    
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          <a class="blog-nav-item" href="/post/create/">Write A Blog</a>
        
	</nav>

      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">ProBlogger</h1>
        
      </div>

      <div class="row">

        <div class="col-sm-10 blog-main">

          {% block content%}
          {% for post in object_list %}
          {% if post.image %}
          
          	<a href="{{ post.get_absolute_url }}"><img class="img-responsive" src="{{ post.image.url }}"></a>

          {% endif %}
          <div class="blog-post">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
           </div>
            
      <div class ="post_meta">
      <small>{{ post.timestamp|timesince }} ago by {{post.author}}</small>
      </div>

      <div class ="post_body">
      {{ post.content|safe|linebreaks|truncatechars:120}}
      </div> 
	
      {% endfor %}
      <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{page_request_var}}={{ object_list.previous_page_number }}&q={{ request.GET.q}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{page_request_var}}={{ object_list.next_page_number }}&q={{ request.GET.q}}">next</a>
        {% endif %}
    </span>
	</div>
               
      </div>
      {% endblock %}  
        </div><!-- /.blog-main -->
      </div><!-- /.row -->
      </div><!-- /.container -->

    <footer class="blog-footer">
      <p>&copy2016 ProBlogger built on <a href="https://www.djangoproject.com/">Django</a> by <a href="https://github.com/rohitchopra32">@Rohit Chopra</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <script src="{% static 'static/jquery.min.js' %}"></script>
    <script src="{% static 'static/bootstrap.min.js' %}"></script>
    
    
</body></html>

templates/post_detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProBlogger</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/blog.css" rel="stylesheet">
     <script src="/static/js/confirm-bootstrap.js"></script>

  </head>

  <body>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/post">Home</a>
          <a class="blog-nav-item" href="/post/create/">Write A Blog</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">ProBlogger</h1>
        
      </div>

      <div class="row">
        {% block content%}
        <div class="col-sm-8 blog-main">
        <div class="thumbnail">
          {% if instance.image %}
        	<img src="{{ instance.image.url }}" class="img-responsive"/>
          {% endif %}
          </div>
          <div class="blog-post">
            <h2 class="blog-post-title"> </h2>
            <p class="blog-post-meta"></p>
			<a href="/blog/{{post.id}}">{{ instance.title }}</a>
			<div class ="post_meta">
				{{ instance.timestamp|timesince }} ago by {{instance.author}}
        <div class="pull-right">
          <a  class="btn btn-primary btn-sm" href="{% url 'post:update' id=instance.id %}">Edit</a>
          <!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
  Delete
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Delete!!</h4>
      </div>
      <div class="modal-body">
        <h4 class="modal-body"> Are You Sure?</h4>
      </div>
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Close</a>
        <a class="btn btn-primary" href="{% url 'post:delete' id=instance.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
        </div>

			<br>
      <p>
      <div class="fb-like" data-href="{{ request.build_absolute_url}}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div></p>
      </div>

      </div>
<br>
			<div class ="post_body">
				{{ instance.content|safe|linebreaks}}
			</div>


        </div><!-- /.blog-main -->
        <div class="fb-comments" data-href="{{ request.build_absolute_url}}" data-numposts="5"></div>
        {% endblock %}            
        <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>&copy2016 ProBlogger built on <a href="https://www.djangoproject.com/">Django</a> by <a href="https://github.com/rohitchopra32">@Rohit Chopra</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>  

</body></html>

templates/post_form.html
{% load staticfiles %}
{% load bootstrap %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProBlogger</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">    
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item" href="/post/">Home</a>
          <a class="blog-nav-item active" href="/post/create/">Write A Blog</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">ProBlogger</h1>
        
      </div>

      <div class="row">

        <div class="col-sm-10">
        	{% block content%}
				<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group">
				{{ form|bootstrap }}
				<input type="submit" class="btn btn-default" value="create post">           
        </div>
			{% endblock %}            
			</div>

        </div><!-- /.blog-main -->

        
      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>&copy2016 ProBlogger built on <a href="https://www.djangoproject.com/">Django</a> by <a href="https://github.com/rohitchopra32">@Rohit Chopra</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


     <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>  

</body></html>